const fs = require('fs');

const nav = `<a class="skip" href="#main">Saltar para o conteúdo</a>
<div class="announcement">NASCIDA EM MOÇAMBIQUE. CRIADA PARA TE EXPRESSARES. <span>EST. 2025</span></div>
<header class="header">
  <a class="wordmark" href="index.html" aria-label="God Seven Line — Início">GOD SEVEN<span>LINE®</span></a>
  <button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu <span>☰</span></button>
  <nav id="navigation" aria-label="Navegação principal"><a href="produtos.html">Colecção</a><a href="servicos.html">Personaliza</a><a href="sobre.html">A nossa história</a><a href="Localizacao.html">Encontra-nos</a></nav>
  <a class="header-contact" href="contactos.html">Vamos conversar <span>↗</span></a>
</header>`;

const footer = `<section class="community"><div><p class="eyebrow">FAZ PARTE DA NOSSA HISTÓRIA</p><h2>A tua gente. A tua linha.</h2></div><a class="button light" href="https://www.instagram.com/godsevenline_estampagem/" target="_blank" rel="noopener">Segue no Instagram <span>↗</span></a></section>
<footer><div class="footer-top"><a class="wordmark" href="index.html">GOD SEVEN<span>LINE®</span></a><p>Não seguimos tendências. Criamos.<br>De Moçambique, com propósito.</p><nav aria-label="Rodapé"><a href="produtos.html">Colecção</a><a href="servicos.html">Personalização</a><a href="contactos.html">Contactos</a><a href="Localizacao.html">Localização</a></nav></div><div class="footer-bottom"><span>© 2026 God Seven Line</span><span>Cada linha conta uma história.</span><a href="#top">Voltar ao topo ↑</a></div></footer>`;

const shell = (title, body) => `<!DOCTYPE html><html lang="pt-MZ"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="theme-color" content="#f5f3ed"><meta name="description" content="God Seven Line. Roupa e personalização com identidade moçambicana. Descobre a colecção e encomenda pelo WhatsApp."><title>${title} — God Seven Line</title><link rel="stylesheet" href="god-seven.css"><script src="store.js" defer></script></head><body id="top">${nav}<main id="main">${body}</main>${footer}</body></html>`;

const products = [
  {id:'tee', name:'T-shirt Seven', category:'T-shirts', color:'Verde', image:'IMG-20260617-WA0006(1).jpg', tag:'ESSENCIAL'},
  {id:'polo', name:'Polo Seven', category:'Polos', color:'Rosa / Vermelho', image:'IMG-20260617-WA0008(1).jpg', tag:'IDENTIDADE'},
  {id:'custom', name:'A tua estampa', category:'Personalizados', color:'T-shirts e sacolas', image:'IMG-20260708-WA0010(1).jpg', tag:'FEITO À TUA MEDIDA'},
  {id:'street', name:'Seven Street Tee', category:'T-shirts', color:'Branco', image:'IMG_20260829_163923_927.webp', tag:'STREET EDITION'},
  {id:'black', name:'Seven Signature', category:'Polos', color:'Preto', image:'IMG_20260829_163739_990.webp', tag:'SIGNATURE'},
  {id:'canvas', name:'Sacola Personalizada', category:'Personalizados', color:'Natural', image:'img_1788013265582.jpg', tag:'CRIA A TUA'}
];

const card = p => `<article class="product" data-category="${p.category}" data-name="${p.name.toLowerCase()}"><button class="product-image" data-product="${p.id}" aria-label="Ver ${p.name}"><img src="${p.image}" alt="${p.name} — ${p.color}" loading="lazy"><span class="product-tag">${p.tag}</span><span class="product-plus" aria-hidden="true">↗</span></button><div class="product-info"><div><h3><button data-product="${p.id}">${p.name}</button></h3><p>${p.color}</p></div><span class="price">Preço sob consulta</span></div></article>`;
const cards = products.map(card).join('');
const featuredCards = products.slice(0, 3).map(card).join('');

const home = `<section class="hero"><div class="hero-copy"><p class="eyebrow"><span class="dot"></span> INDEPENDENTE. MOÇAMBICANA. ORIGINAL.</p><h1>VESTE A<br>TUA <em>HISTÓRIA.</em></h1><p class="hero-description">Mais do que roupa. Uma forma de seres tu.<br>Peças com atitude, criadas para a tua próxima história.</p><a class="button" href="produtos.html">Explorar a colecção <span>↗</span></a><div class="hero-bottom"><span>ESTILO SEM REGRAS.<br>IDENTIDADE SEM LIMITES.</span><a href="#collection" aria-label="Descobrir a colecção">↓</a></div></div><div class="hero-photo"><img src="IMG-20260617-WA0008(1).jpg" alt="Duas jovens com polos God Seven Line rosa e vermelho" fetchpriority="high"><span class="photo-caption">THE SEVEN WAY OF LIFE.</span><div class="photo-label"><span>GOD SEVEN LINE</span><span>MOZAMBIQUE ↗</span></div></div></section>
<div class="ticker" aria-label="Identidade da marca"><div class="ticker-track"><span>CADA LINHA CONTA UMA HISTÓRIA</span><b>✳</b><span>FEITO PARA SERES TU</span><b>✳</b><span>GOD SEVEN LINE</span><b>✳</b><span aria-hidden="true">CADA LINHA CONTA UMA HISTÓRIA</span><b aria-hidden="true">✳</b><span aria-hidden="true">FEITO PARA SERES TU</span><b aria-hidden="true">✳</b><span aria-hidden="true">GOD SEVEN LINE</span><b aria-hidden="true">✳</b></div></div>
<section class="collection section" id="collection"><div class="section-heading"><div><p class="eyebrow">ESCOLHE A TUA LINHA</p><h2>O teu próximo favorito.</h2></div><a class="text-link" href="produtos.html">Ver toda a colecção ↗</a></div><div class="product-grid">${featuredCards}</div><p class="collection-note">Gostaste de uma peça? Escolhe o teu estilo e fala connosco para confirmar preço e disponibilidade.</p></section>
<section class="brand-story"><div class="story-photo"><img src="IMG-20260617-WA0006(1).jpg" alt="T-shirt verde Seven usada ao ar livre em Moçambique" loading="lazy"><span>07 / LINHAS COM PROPÓSITO</span></div><div class="story-copy"><p class="eyebrow">RAÍZES LOCAIS. ATITUDE SEM LIMITES.</p><h2>Não seguimos<br>tendências.<br><em>Criamos.</em></h2><p>Nascemos em Moçambique para quem quer vestir mais do que roupa. Cada peça carrega uma história, uma identidade e um propósito. Agora, faz parte da tua.</p><a class="text-link" href="sobre.html">Conhece a nossa história ↗</a></div></section>
<section class="custom section"><p class="eyebrow">A TUA IDEIA. A NOSSA ESTAMPA.</p><h2>Única. Como tu.</h2><p>Uma t-shirt, uma sacola ou uma ideia fora da caixa.<br>Dá vida à tua criatividade com a nossa personalização.</p><a class="button" href="servicos.html">Criar a minha peça <span>↗</span></a><span class="custom-art" aria-hidden="true">✳</span></section>`;

fs.writeFileSync('index.html', shell('Veste a tua história', home));
fs.writeFileSync('God-seven-line.html', shell('Veste a tua história', home));
fs.writeFileSync('produtos.html', shell('Colecção', `<section class="section catalog"><p class="eyebrow">PEÇAS COM IDENTIDADE</p><h1>A tua próxima linha.</h1><p>Descobre o teu estilo. Confirma preços, tamanhos e disponibilidade connosco.</p><div class="catalog-tools"><div class="filters" aria-label="Filtrar colecção">${['Todos','T-shirts','Polos','Personalizados'].map((c,i)=>`<button data-filter="${c}" aria-pressed="${i===0}">${c}</button>`).join('')}</div><label class="search">Pesquisar <input type="search" id="search" placeholder="Procura uma peça…"></label></div><p id="result-count" aria-live="polite">${products.length} peças</p><div class="product-grid">${cards}</div><p id="empty" hidden>Não encontrámos essa peça. Experimenta outra pesquisa ou categoria.</p></section>`));

const services = `<section class="page-hero split-hero"><div class="page-hero-copy"><p class="eyebrow">PERSONALIZA / À TUA MANEIRA</p><h1>A tua ideia.<br><em>A tua peça.</em></h1><p>Transformamos desenhos, frases, marcas e memórias em roupa que só tu podes vestir.</p><a class="button" href="https://wa.me/258870204282?text=Olá%2C%20quero%20personalizar%20uma%20peça" target="_blank" rel="noopener">Começar no WhatsApp <span>↗</span></a></div><div class="page-hero-image"><img src="file_0000000051948243be34b4173302469c.png" alt="Exemplos de vestuário que pode ser personalizado"><span>DA IDEIA À RUA / 01</span></div></section>
<section class="service-intro section reveal"><div><p class="eyebrow">O QUE PODES CRIAR</p><h2>Sem limites.<br>Só possibilidades.</h2></div><p>Personalizamos t-shirts, polos, hoodies, uniformes e sacolas. Podes trazer uma arte pronta ou apenas uma ideia: ajudamos a escolher a peça, a técnica e a posição que melhor conta a tua história.</p></section>
<section class="service-cards section"><article class="feature-card reveal"><span>01</span><div class="feature-icon">✦</div><h3>Serigrafia</h3><p>Cores sólidas e alta durabilidade. Ideal para equipas, eventos, marcas e encomendas em quantidade.</p></article><article class="feature-card reveal"><span>02</span><div class="feature-icon">◉</div><h3>Impressão DTF</h3><p>Detalhes nítidos, muitas cores e liberdade criativa. Perfeita para peças únicas e artes complexas.</p></article><article class="feature-card reveal"><span>03</span><div class="feature-icon">↗</div><h3>Apoio criativo</h3><p>Ainda não tens a arte final? Conversamos contigo e encontramos uma solução que funciona na peça.</p></article></section>
<section class="process section reveal"><p class="eyebrow">SIMPLES DO INÍCIO AO FIM</p><h2>Como funciona.</h2><div class="process-line"><article><b>01</b><h3>Partilha a ideia</h3><p>Envia a imagem, frase, logótipo ou referência pelo WhatsApp.</p></article><article><b>02</b><h3>Escolhe os detalhes</h3><p>Definimos peça, cor, tamanho, quantidade, técnica e prazo.</p></article><article><b>03</b><h3>Aprova e criamos</h3><p>Confirmas a proposta e produzimos tudo com atenção.</p></article><article><b>04</b><h3>Recebe e veste</h3><p>Combinamos o levantamento ou a melhor forma de entrega.</p></article></div></section>
<section class="material-band"><div><strong>100%</strong><span>ALGODÃO<br>DISPONÍVEL</span></div><div><strong>02</strong><span>TÉCNICAS<br>DE IMPRESSÃO</span></div><div><strong>01</strong><span>PEÇA ÚNICA<br>COMO TU</span></div></section>`;

const story = `<section class="page-hero story-hero"><div class="story-title"><p class="eyebrow">A NOSSA HISTÓRIA / DESDE 2025</p><h1>SETE LINHAS.<br><em>UM PROPÓSITO.</em></h1></div><div class="story-hero-grid"><img src="IMG_20260829_163739_990.webp" alt="Jovens a vestir God Seven Line"><div class="story-manifesto"><span>✳</span><p>Algumas linhas foram tortas. Outras, rectas. Em todas elas, Deus guiou o caminho.</p></div></div></section>
<section class="origin section reveal"><div><p class="eyebrow">19 JULHO / 2025</p><h2>Onde tudo começou.</h2></div><div><p>A God Seven Line nasceu em Moçambique depois de várias etapas que se tornaram sete linhas. Cada uma marcou a nossa história e ajudou a construir a marca que somos hoje.</p><p>O mais importante é que algumas linhas ainda não foram escritas. A história continua contigo, em cada peça e em cada ideia que ganha vida.</p></div></section>
<section class="name-grid section"><article class="name-card reveal"><strong>GOD</strong><h3>Direcção</h3><p>Deus esteve presente em cada caminho, nos fáceis e nos difíceis.</p></article><article class="name-card dark reveal"><strong>SEVEN</strong><h3>Propósito</h3><p>O número sete representa perfeição, propósito e ciclos completados.</p></article><article class="name-card accent reveal"><strong>LINE</strong><h3>História</h3><p>Cada linha mostra um caminho vivido e uma nova história por escrever.</p></article></section>
<section class="values section reveal"><div><p class="eyebrow">O QUE NOS MOVE</p><h2>Roupa com<br>significado.</h2></div><div class="value-list"><p><span>01</span><strong>Identidade</strong> Peças para quem não tem medo de se destacar.</p><p><span>02</span><strong>Qualidade</strong> Algodão, dry fit e tintas feitas para durar.</p><p><span>03</span><strong>Comunidade</strong> Uma marca local construída com quem a veste.</p><p><span>04</span><strong>Futuro</strong> Novas linhas, uma loja física e histórias além de Moçambique.</p></div></section>`;

const location = `<section class="page-hero location-hero"><div class="page-hero-copy"><p class="eyebrow">ENCONTRA-NOS / MANHIÇA</p><h1>Vem viver<br><em>a linha.</em></h1><p>Vê as peças de perto, conversa connosco e começa a tua próxima história.</p><a class="button" href="https://wa.me/258870204282?text=Olá%2C%20preciso%20de%20indicações%20para%20chegar%20à%20loja" target="_blank" rel="noopener">Pedir indicações <span>↗</span></a></div><div class="location-art"><span class="map-pin">7</span><div class="road one"></div><div class="road two"></div><p>VILA DA<br><strong>MANHIÇA</strong></p></div></section>
<section class="visit-grid section reveal"><article><p class="eyebrow">01 / MORADA</p><h2>Em frente ao<br>Millennium BIM.</h2><p>Vila da Manhiça, Moçambique. Procura a identidade God Seven Line.</p></article><article><p class="eyebrow">02 / HORÁRIO</p><div class="hours"><p><span>Segunda — Sexta</span><strong>08h00 — 17h00</strong></p><p><span>Sábado</span><strong>08h00 — 17h00</strong></p><p><span>Domingo</span><strong>Encerrado</strong></p></div></article></section>
<section class="location-photo reveal"><img src="IMG_20260829_164011_637.webp" alt="Comunidade God Seven Line em Moçambique"><div><p class="eyebrow">ANTES DE VIRES</p><h2>Confirma a tua visita.</h2><p>Envia uma mensagem para confirmar disponibilidade de peças, tamanhos e atendimento.</p><a class="text-link" href="contactos.html">Falar connosco ↗</a></div></section>`;

fs.writeFileSync('servicos.html', shell('Personalização', services));
fs.writeFileSync('sobre.html', shell('A nossa história', story));
fs.writeFileSync('Localizacao.html', shell('Encontra-nos', location));

fs.writeFileSync('contactos.html', shell('Contactos', `<section class="sobre-conteudo"><p class="eyebrow">ESTAMOS POR AQUI</p><h1>Vamos conversar.</h1><p class="intro">Uma peça que te chamou a atenção? Uma ideia para personalizar? Fala connosco.</p><div class="contact-grid"><a class="contact-card" href="https://wa.me/258870204282" target="_blank" rel="noopener"><span>01 / ENCOMENDAS</span><h2>WhatsApp ↗</h2><p>+258 87 020 4282</p><p>Preços, tamanhos e personalização.</p></a><a class="contact-card" href="https://www.instagram.com/godsevenline_estampagem/" target="_blank" rel="noopener"><span>02 / COMUNIDADE</span><h2>Instagram ↗</h2><p>@godsevenline_estampagem</p><p>Inspiração e novidades da marca.</p></a></div><div class="sobre-bloco"><h2>Vem conhecer-nos.</h2><p>Vila da Manhiça, em frente ao Millennium BIM.</p><p>Segunda a Sábado · 08h00 – 17h00</p><a class="text-link" href="Localizacao.html">Ver localização ↗</a></div></section>`));

fs.writeFileSync('products.json', JSON.stringify(products, null, 2));
